- name: "[mysql-db] installing dependencies"
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - mysql-server
    - python-mysqldb

- name: "[mysql-db] starting mysql server"
  service: name=mysql state=started enabled=yes
