---
- hosts:
    - wavemanda.la

  sudo: yes
  user: root
  vars:
    prosody_tls_key_path: /etc/prosody/certs/wavemanda.la.key
    prosody_tls_cert_path: /etc/prosody/certs/wavemanda.la.cert
    restund_public_ip_address: 45.55.126.214
    wavemandala_mysql_user: xmpp
    wavemandala_mysql_db: prosody
    wavemandala_mysql_password: l3m0np4rty
    root_domain: wavemanda.la
    local_repository_root_path: "{{ playbook_dir }}/.."
  vars_files:
    - "wavemandala-vault.yml"
  roles:
    - base
    - ssl
    - web
    - postfix
    - prosody
